#cloud-config

users:
  - default
  - name: alama-test
    shell: /bin/bash
    lock-passwd: false
    ssh_pwauth: True
    chpasswd: { expire: False }
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
#    ssh_authorized_keys:
#      - <SSH_PUBLIC_KEY>

package_update: true
packages:
  - qemu-guest-agent
  - avahi-daemon
runcmd:
  - systemctl start qemu-guest-agent.service
  - systemctl start avahi-daemon

hostname: ${hostname}
create_hostname_file: true
